apiVersion: v1
kind: Service
metadata:
  name: {{ include "rook-ceph-config.fullname" . }}
  labels:
    {{- include "rook-ceph-config.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https-dashboard
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8443
  selector:
    app: rook-ceph-mgr
    mgr_role: active
    rook_cluster: rook-ceph
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}  
